# Generated by Django 6.0.7 on 2026-07-23 03:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sub', models.CharField(blank=True, max_length=150, verbose_name='ชื่อรอง (ภาษาลาว)')),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=100)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('qr', models.ImageField(blank=True, null=True, upload_to='bank_qr/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('slug', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Icon name from assets/icons.js', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('percent_off', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='NexByte', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('contact_fb', models.URLField(blank=True, default='https://facebook.com/nexbytecomputer')),
                ('contact_wa', models.CharField(blank=True, default='8562055551234', max_length=30)),
                ('stats_enabled', models.BooleanField(default=True)),
                ('stat_metric_1', models.CharField(choices=[('members', 'สมาชิกร้านเรา'), ('sales', 'ยอดขายรวม'), ('completedOrders', 'ออเดอร์สำเร็จ'), ('totalOrders', 'ออเดอร์ทั้งหมด'), ('products', 'สินค้าทั้งหมด')], default='members', max_length=20)),
                ('stat_metric_2', models.CharField(choices=[('members', 'สมาชิกร้านเรา'), ('sales', 'ยอดขายรวม'), ('completedOrders', 'ออเดอร์สำเร็จ'), ('totalOrders', 'ออเดอร์ทั้งหมด'), ('products', 'สินค้าทั้งหมด')], default='sales', max_length=20)),
                ('stat_metric_3', models.CharField(choices=[('members', 'สมาชิกร้านเรา'), ('sales', 'ยอดขายรวม'), ('completedOrders', 'ออเดอร์สำเร็จ'), ('totalOrders', 'ออเดอร์ทั้งหมด'), ('products', 'สินค้าทั้งหมด')], default='completedOrders', max_length=20)),
                ('stat_override_1', models.FloatField(blank=True, help_text='เว้นว่าง = ใช้ค่าจริง', null=True)),
                ('stat_override_2', models.FloatField(blank=True, null=True)),
                ('stat_override_3', models.FloatField(blank=True, null=True)),
                ('theme_primary', models.CharField(default='#8b7cf6', max_length=9)),
                ('theme_secondary', models.CharField(default='#a78bfa', max_length=9)),
                ('theme_background', models.CharField(default='#0a0913', max_length=9)),
                ('theme_text', models.CharField(default='#f3f1fa', max_length=9)),
                ('theme_card_bg', models.CharField(default='#12101f', max_length=9)),
                ('theme_button', models.CharField(default='#9686f9', max_length=9)),
                ('theme_border', models.CharField(default='#ffffff', max_length=9)),
                ('theme_header_bg', models.CharField(default='#0a0913', max_length=9)),
                ('theme_bg_image', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='บ้าน')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='เมือง')),
                ('province', models.CharField(blank=True, max_length=120, verbose_name='แขวง')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'รอชำระเงิน'), ('preparing', 'กำลังเตรียมสินค้า'), ('shipping', 'กำลังจัดส่ง'), ('delivered', 'จัดส่งสำเร็จ')], default='pending', max_length=20)),
                ('shipping_name', models.CharField(max_length=150)),
                ('shipping_phone', models.CharField(max_length=30)),
                ('shipping_province', models.CharField(max_length=120, verbose_name='แขวง')),
                ('shipping_city', models.CharField(max_length=120, verbose_name='เมือง')),
                ('shipping_village', models.CharField(max_length=150, verbose_name='บ้าน')),
                ('carrier', models.CharField(choices=[('anousith', 'Anousith Logistics'), ('rungaroon', 'รุ่งอรุณ ขนส่ง')], default='anousith', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('ldb', 'LDB Bank'), ('one', 'One Bank')], max_length=20)),
                ('payment_slip', models.ImageField(blank=True, null=True, upload_to='slips/')),
                ('coupon_code', models.CharField(blank=True, max_length=30)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('shipping_fee', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(help_text='ราคาเป็นกีบ (₭)')),
                ('old_price', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(default='💻', help_text='Emoji fallback when no image is set', max_length=10)),
                ('tag', models.CharField(blank=True, max_length=40)),
                ('desc', models.TextField(blank=True)),
                ('specs', models.JSONField(blank=True, default=list, help_text='List of spec strings')),
                ('featured', models.BooleanField(default=True, help_text='Show on homepage + all categories, not just its own category')),
                ('best_seller', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('unit_price', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'subcategories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('products', models.ManyToManyField(blank=True, related_name='wishlisted_by', to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
