# Generated by Django 6.0.7 on 2026-07-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='uses_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='custom_css',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_radius',
            field=models.CharField(default='12px', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(max_length=120, verbose_name='ເມືອງ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_province',
            field=models.CharField(max_length=120, verbose_name='ແຂວງ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_village',
            field=models.CharField(max_length=150, verbose_name='ບ້ານ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='ບ້ານ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='ເມືອງ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=120, verbose_name='ແຂວງ'),
        ),
    ]
