# Generated by Django 6.0.7 on 2026-07-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_coupon_max_uses_coupon_uses_count_coupon_valid_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sales_adjustment',
            field=models.BigIntegerField(default=0, help_text='ยอดขายที่เก็บไว้จากคำสั่งซื้อที่ถูกลบ + ปรับด้วยมือ (บวกเข้ากับยอดขายรวมที่คำนวณจริง)'),
        ),
    ]
