# Generated by Django 6.0.7 on 2026-07-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sitesettings_sales_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text='ໃສ່ລິ້ງຮູບແທນການອັບໂຫຼດໄຟລ໌ (ຖ້າໃສ່ ຈະໃຊ້ລິ້ງນີ້ແທນ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_bg_image_url',
            field=models.URLField(blank=True, default='', help_text='ໃສ່ລິ້ງຮູບແທນການອັບໂຫຼດໄຟລ໌ (ຖ້າໃສ່ ຈະໃຊ້ລິ້ງນີ້ແທນ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_footer_bg',
            field=models.CharField(default='#0a0913', max_length=9),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_stat_icon',
            field=models.CharField(default='#8b7cf6', max_length=9),
        ),
    ]
