# Generated by Django 6.0.7 on 2026-07-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sitesettings_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='theme_panel_deep',
            field=models.CharField(default='#1c1832', max_length=9),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_tabbar_bg',
            field=models.CharField(default='#171429', max_length=9),
        ),
    ]
