# Generated by Django 6.0.7 on 2026-07-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_sitesettings_theme_panel_deep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('ldb', 'LDB Bank'), ('one', 'BCEL Bank')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='stat_metric_1',
            field=models.CharField(choices=[('members', 'ສະມາຊິກຮ້ານເຮົາ'), ('sales', 'ຍອດຂາຍລວມ'), ('completedOrders', 'ອໍເດີສຳເລັດ'), ('totalOrders', 'ອໍເດີທັງໝົດ'), ('products', 'ສິນຄ້າທັງໝົດ')], default='members', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='stat_metric_2',
            field=models.CharField(choices=[('members', 'ສະມາຊິກຮ້ານເຮົາ'), ('sales', 'ຍອດຂາຍລວມ'), ('completedOrders', 'ອໍເດີສຳເລັດ'), ('totalOrders', 'ອໍເດີທັງໝົດ'), ('products', 'ສິນຄ້າທັງໝົດ')], default='sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='stat_metric_3',
            field=models.CharField(choices=[('members', 'ສະມາຊິກຮ້ານເຮົາ'), ('sales', 'ຍອດຂາຍລວມ'), ('completedOrders', 'ອໍເດີສຳເລັດ'), ('totalOrders', 'ອໍເດີທັງໝົດ'), ('products', 'ສິນຄ້າທັງໝົດ')], default='completedOrders', max_length=20),
        ),
    ]
