# Generated by Django 6.0.7 on 2026-07-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='brands', to='store.category'),
        ),
    ]
