# Generated by Django 6.0.7 on 2026-07-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_brand_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='popup_ad_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='popup_ad_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='popup_ad_link',
            field=models.URLField(blank=True, default='', help_text='ລິ້ງເມື່ອກົດໃສ່ຮູບ (ເວັ້ນວ່າງໄດ້ຖ້າບໍ່ຕ້ອງການ)'),
        ),
    ]
