# Generated by Django 6.0.7 on 2026-07-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_sitesettings_popup_ad_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_link',
            field=models.URLField(blank=True, default='', help_text='ລິ້ງແຫຼ່ງສິນຄ້າ (ບ່ອນສັ່ງເອົາມາຂາຍ) — ເຫັນສະເພາະໜ້າແອັດມິນ, ລູກຄ້າບໍ່ເຫັນ'),
        ),
    ]
