# Generated by Django 6.0.7 on 2026-07-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_branch',
            field=models.CharField(blank=True, max_length=150, verbose_name='ສາຂາ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'ລໍຖ້າຊຳລະເງິນ'), ('preparing', 'ກຳລັງກຽມສິນຄ້າ'), ('shipping', 'ກຳລັງຈັດສົ່ງ'), ('delivered', 'ຈັດສົ່ງສຳເລັດ')], default='pending', max_length=20),
        ),
    ]
