# Generated by Django 6.0.7 on 2026-07-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_shipping_branch_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='carrier_anousith_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='carrier_rungaroon_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_bcel_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_ldb_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
