# Generated by Django 6.0.7 on 2026-07-24 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_sitesettings_carrier_anousith_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='source_link',
            field=models.TextField(blank=True, default='', help_text='ລິ້ງແຫຼ່ງສິນຄ້າ (ບ່ອນສັ່ງເອົາມາຂາຍ) — ເຫັນສະເພາະໜ້າແອັດມິນ, ລູກຄ້າບໍ່ເຫັນ', validators=[django.core.validators.URLValidator()]),
        ),
    ]
