# Generated by Django 6.0.7 on 2026-07-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_source_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_preorder',
            field=models.BooleanField(default=False, help_text='ເປີດຂາຍແບບພຣີອໍເດີ້ (ລູກຄ້າສັ່ງຊື້ໄດ້ເຖິງແມ່ນສິນຄ້າໝົດຄັງ)'),
        ),
    ]
