# Generated by Django 6.0.7 on 2026-07-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_is_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_notify_email',
            field=models.EmailField(blank=True, default='', help_text='ອີເມວຮັບແຈ້ງເຕືອນເມື່ອມີອໍເດີ້ໃໝ່ເຂົ້າມາ (ເວັ້ນວ່າງ = ບໍ່ສົ່ງແຈ້ງເຕືອນ)', max_length=254),
        ),
    ]
