# Generated by Django 6.0.7 on 2026-07-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_sitesettings_admin_notify_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_branch',
            field=models.CharField(default='', max_length=150, verbose_name='ສາຂາ'),
        ),
    ]
