# Generated by Django 6.0.7 on 2026-07-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_order_shipping_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='ໃສ່ລິ້ງຮູບແທນການອັບໂຫຼດໄຟລ໌ (ຖ້າໃສ່ ຈະໃຊ້ລິ້ງນີ້ແທນ)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
