# Generated by Django 6.0.7 on 2026-07-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_productimage_image_url_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='price_calc_markup_percent',
            field=models.DecimalField(decimal_places=2, default=25, help_text='ເປີເຊັນກຳໄລເລີ່ມຕົ້ນໃນເຄື່ອງຄິດໄລ່ລາຄາຕົ້ນທາງ (ແກ້ໄຂໄດ້ຕໍ່ສິນຄ້າ)', max_digits=5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_calc_thb_rate',
            field=models.DecimalField(decimal_places=2, default=620, help_text='ອັດຕາແລກປ່ຽນ: 1 ບາດໄທ (฿) ເທົ່າກັບຈັກກີບ (₭) — ໃຊ້ໃນເຄື່ອງຄິດໄລ່ລາຄາຕົ້ນທາງໜ້າເພີ່ມ/ແກ້ໄຂສິນຄ້າ', max_digits=10),
        ),
    ]
