# Generated by Django 6.0.7 on 2026-08-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_sitesettings_price_calc_markup_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='ລິ້ງວິດີໂອສິນຄ້າ (YouTube, Facebook, TikTok ເປັນຕົ້ນ) — ລູກຄ້າຈະກົດເບິ່ງໄດ້ຢູ່ໜ້າສິນຄ້າ'),
        ),
    ]
