# Generated by Django 6.0.7 on 2026-08-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_fit',
            field=models.CharField(choices=[('contain', 'ກອບພໍດີກ່ອງ (Contain — ຮູບຄົບບໍ່ຕັດຂອບ)'), ('cover', 'ກອບເຕັມກ່ອງ (Cover — ຮູບເຕັມກ່ອງ)'), ('original', 'ຂະໜາດເດີມ (Original — ອັດຕາສ່ວນເດີມ)')], default='contain', help_text='ຮູບແບບກອບຊະໜາດຮູບສິນຄ້າ (Contain: ພໍດີກ່ອງ / Cover: ເຕັມກ່ອງ / Original: ຂະໜາດເດີມ)', max_length=20),
        ),
    ]
