# Generated by Django 6.0.7 on 2026-08-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_image_fit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_padding',
            field=models.PositiveIntegerField(default=16, help_text='ໄລຍະຫ່າງຂອບກອບ (px)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_zoom',
            field=models.PositiveIntegerField(default=100, help_text='ຊູມຮູບ (%) ເຊັ່ນ 100, 110, 120'),
        ),
    ]
