# Generated by Django 6.0.7 on 2026-08-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_image_padding_product_image_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_bg',
            field=models.CharField(default='#ffffff', help_text='ສີພື້ນຫຼັງກອບຮູບ (#ffffff = ສີຂາວ, #f4f5f8 = ສີເທາະ, #12101f = ສີເຂັ້ມ)', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='image_blend',
            field=models.BooleanField(default=False, help_text='ລົບພື້ນຫຼັງສີຂາວອອກ (Multiply Blend Mode — ໃຫ້ພື້ນຫຼັງສີຂາວຂອງຮູບເນື້ອດຽວກັນກັບກອບ)'),
        ),
    ]
