# Generated by Django 6.0.7 on 2026-08-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_product_image_bg_product_image_blend'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_thumb',
            field=models.URLField(blank=True, default='', help_text='ລິ້ງຮູບ Thumbnail ຂອງວິດີໂອ (ຖ້າບໍ່ໃສ່ ລະບົບຈະດຶງຮູບຈາກວິດີໂອອັດໂນມັດ)'),
        ),
    ]
